fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: '4.4.0'
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: '2.0.0'
  symlinks:
    pf: "#{source_dir}"
